version: 2
jobs:
  docker:
    docker:
      - image: docker:18.06-dind
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            docker info
            docker version
  machine:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            docker info
            docker version
  macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            docker info
            docker version

workflows:
  version: 2
  build:
    jobs:
      - docker
      - machine
      - macos
