version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            docker info
            docker version
