version: 2.1
parameters:
  var1:
    type: string
    default: ''
  var2:
    type: string
    default: ''
  var3:
    type: integer
    default: ''
  var2:
    type: boolean
    default: ''
workflows:
  version: 2
  run_build:
    when: << pipeline.parameters.var1 >>
    jobs:
    - build
jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      var1: << pipeline.parameters.var1 >>
      var2: << pipeline.parameters.var2 >>
      var3: << pipeline.parameters.var3 >>
      var4: << pipeline.parameters.var4 >>
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
      - run:
          name: debug
          command: |
            echo hi
            exit 0
            echo bye
