version: 2.1
parameters:
  var1:
    type: string
    default: ''
  var2:
    type: string
    default: ''
  var3:
    type: string
    default: ''
  var4:
    type: string
    default: ''
workflows:
  version: 2
  run_build:
    # when: << pipeline.parameters.var1 >>
    jobs:
    - build-docker1
    - build-machine1
    - build-machine2
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-docker1:
    docker:
      - image: docker:18.09.2-git
    environment:
      var1: << pipeline.parameters.var1 >>
      var2: << pipeline.parameters.var2 >>
      var3: << pipeline.parameters.var3 >>
      var4: << pipeline.parameters.var4 >>
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
      - run:
          name: debug
          command: |
            echo hi
            exit 0
            echo bye
      - slack/status:
          fail_only: false
          webhook: ${SLACK_WEBHOOK}
  build-machine1:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    environment:
      var1: << pipeline.parameters.var1 >>
      var2: << pipeline.parameters.var2 >>
      var3: << pipeline.parameters.var3 >>
      var4: << pipeline.parameters.var4 >>
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
      - run:
          name: Debug job.environment variables
          command: |
            BODY=$( echo '{}' | jq '
            {
                "build_num": env.CIRCLE_BUILD_NUM,
                "username": env.CIRCLE_PROJECT_USERNAME,
                "reponame": env.CIRCLE_PROJECT_REPONAME,
                "branch": env.CIRCLE_BRANCH,
                "build_parameters": {
                    "var1": env.var1,
                    "var2": env.var2,
                    "var3": env.var3,
                    "var4": env.var4
                }
            }
            ' )
            echo "BODY: $BODY"
      - run:
          name: Debug circleci env.* variables
          command: |
            BODY=$( echo '{}' | jq '
            {
                "build_num": "$CIRCLE_BUILD_NUM",
                "username": "$CIRCLE_PROJECT_USERNAME",
                "reponame": "$CIRCLE_PROJECT_REPONAME",
                "branch": "$CIRCLE_BRANCH",
                "build_parameters": {
                    "var1": "$var1",
                    "var2": "$var2",
                    "var3": "$var3",
                    "var4": "$var4"
                }
            }
            ' )
            echo "BODY: $BODY"
      - run:
          name: Debug circleci env.* variables interpolation with .sh file
          command: |
            ./debug-circleci-env-variables.sh
      - run:
          name: Debug circleci env.* variables
          command: |
            echo env.JOB_NUMBER
            echo env.CIRCLE_PROJECT_USERNAME
            echo env.CIRCLE_PROJECT_REPONAME
            echo env.CIRCLE_BRANCH
      - run:
          name: Debug shell variables
          command: |
            echo "$JOB_NUMBER"
            echo "$CIRCLE_PROJECT_USERNAME"
            echo "$CIRCLE_PROJECT_REPONAME"
            echo "$CIRCLE_BRANCH"
      - run:
          name: tools
          command: |
            jq --help
      - slack/status:
          fail_only: false
          webhook: ${SLACK_WEBHOOK}
  build-machine2:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    environment:
      var1: << pipeline.parameters.var1 >>
      var2: << pipeline.parameters.var2 >>
      var3: << pipeline.parameters.var3 >>
      var4: << pipeline.parameters.var4 >>
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
      - run:
          name: debug
          command: |
            echo hi
            exit 0
            echo bye
      - run:
          name: Build, test, push image
          command: |
            echo dummy
            echo dummy2
            echo dummy3
      - slack/status:
          fail_only: false
          webhook: ${SLACK_WEBHOOK}
