version: 2.1
parameters:
  run_job_build:
    type: boolean
    default: false
  var1:
    type: string
    default: ''
  var2:
    type: string
    default: ''
workflows:
  version: 2
  ci:
    when: << pipeline.parameters.run_job_build >>
    jobs:
    - build
    - send-notification:
        requires:
        - build
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
      - run:
          name: Store cache
          command: |
            echo "$CIRCLE_BUILD_NUM" > /tmp/CIRCLE_BUILD_NUM
      - save_cache:
          key: CIRCLE_BUILD_NUM-{{ checksum "CIRCLE_BUILD_NUM" }}
          paths:
          - /tmp/CIRCLE_BUILD_NUM
  send-notification:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - restore_cache:
        keys:
        - CIRCLE_BUILD_NUM
    - run:
        name: Send notification
        command: |
          cat /tmp/CIRCLE_BUILD_NUM
# notify:
#   webhooks:
#   - url: https://outlook.office.com/webhook/78418f17-b295-40cc-ae37-bfc91463c01e@4e4f53c4-6f09-4818-9c77-020eeb613480/CircleCI/4a2bb892c6014937ba79528601766b78/51073360-bb16-430e-b8d7-e5f40375df1d
#   - url: https://hooks.slack.com/services/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
#   - url: https://startersclan.com/post-build-beta
