version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: system info
          command: |
            echo hello
            echo world
            echo goodbye
      - run:
          name: Print environment variables
          command: |
            printenv
notify:
  webhooks:
  - url: https://outlook.office.com/webhook/78418f17-b295-40cc-ae37-bfc91463c01e@4e4f53c4-6f09-4818-9c77-020eeb613480/CircleCI/4a2bb892c6014937ba79528601766b78/51073360-bb16-430e-b8d7-e5f40375df1d
  - url: https://hooks.slack.com/services/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
  - url: https://startersclan.com/post-build-beta
