version: 2
jobs:
  docker:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            # docker info
            # docker version
            pwd
      - run: |
          i=0; while true; do
              echo "Iteration $(( $i+1 )): $(date)"
              dd if=/dev/zero of="tempfile.$i" bs=1M count=1024
              ls -al "tempfile.$i"
              df -h
              i=$((i + 1))
              echo
              sleep 1
          done
  machine:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: system info
          command: |
            hostname
            whoami
            cat /etc/*release
            lscpu
            free
            df -h
            docker info
            docker version
            pwd
      - run: |
          i=0; while true; do
              echo "Iteration $(( $i+1 )): $(date)"
              dd if=/dev/zero of="tempfile.$i" bs=1M count=1024
              ls -al "tempfile.$i"
              df -h
              i=$((i + 1))
              echo
              sleep 1
          done
  # macos:
  #   macos:
  #     xcode: "9.0"
  #   steps:
  #     - checkout
  #     - run:
  #         name: system info
  #         command: |
  #           hostname
  #           whoami
  #           cat /etc/*release
  #           lscpu
  #           free
  #           df -h
  #           docker info
  #           docker version

workflows:
  version: 2
  build:
    jobs:
      - docker
      - machine
      # - macos
